### ISSUE TITLE
The numerical values in links

### ISSUE THREAD

**Issue by Eevan-zq** [Azure/msccl-tools#15]
The directory is as follows:
![image](https://github.com/user-attachments/assets/ddbde855-11e9-408d-82eb-cbe91d9da79f)

In the `generic.py` file, the values in the `links` list seem to be either 0 or 1, as shown in the following functions:
![image](https://github.com/user-attachments/assets/f3867047-42c2-41e6-9b55-5403443b57d2)

However, in the `nvidia.py` file or other files, the values in the `links` list may be different,the value can be 2 or other, such as:
![image](https://github.com/user-attachments/assets/642efba1-1e98-4e00-b254-42660d7503ef)
![image](https://github.com/user-attachments/assets/176f1960-ea3b-4907-9907-c798ec23b0cb)

Could you tell us what the difference between the two is, and what the values mean? I previously thought that a value of 0 meant disconnected, and 1 meant connected. What does a value of 2 or other numbers represent?

**Comment by Binyang2014** [comment]
The value means how many links are used between two GPUs (edges). Pls refer this white paper: https://images.nvidia.com/content/pdf/dgx1-v100-system-architecture-whitepaper.pdf. For DGX-1 V100, each GPU has 6 nvlinks.  So, it connected with other GPUs with 1 or 2 links. But for new arch, such as A100, each GPU is connected with others with same number of links, so we only use 1, 0 there.
